on:
  pull_request:
    branches:
      - stable
      - release

name: Build and push docker image

env:
  NODE_CONFIG_ENV: ${{ github.base_ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build and push docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: freefeed/freefeed-react-client-${{ github.base_ref }}
        tag_with_ref: true
        tags: latest
        build_args: NODE_CONFIG_ENV=${{ github.base_ref }}
